# -*- encoding: utf-8 -*-
# Israel Fermín Montilla <ferminster@gmail.com>

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def fib(num):
    if num == 0: return 0
    elif num == 1: return 1
    else: return fib(num - 1) + fib(num - 2)

counter = 1
result = n = 0
while (n < 4000000):
    n = fib(counter)
    if n % 2 == 0:
        result += n
    counter += 1

print result
